# settings for state-based tests.
hypothesis:
  max_examples: 5 # 10
  stateful_step_count: 500 # 2000
  report_multiple_bugs: False
  phases:
    explicit: True
    reuse: True
    generate: True
    target: True
    shrink: False
# for command line: --hypothesis-verbosity=verbose (quiet, normal, verbose, debug) -s
# for command line: --hypothesis-show-statistics -s


compiler:
  evm_version: istanbul
  solc:
    version: 0.8.17
    optimizer:
      enabled: true
      runs: 200
    remappings: null
  vyper:
    version: null


# enable output of development artifacts to load with react
dev_deployment_artifacts: false
dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.8.0
    - 0xPolygon/fx-portal@1.0.5
